### ISSUE TITLE
最新的2.0和1.0.12存在报错问题，回退到1.0.11就可用

### ISSUE THREAD

**Issue by wefine** [xiaoxian521/responsive-storage#1]
当使用最新的版本时，pureadmin在页面访问是会报以下的异常：

![image](https://user-images.githubusercontent.com/22292664/177674685-e638be3f-f46b-46b5-bb79-aa13528ecece.png)

但是回退到1.0.11版本就不会报错，还请作者大大检查一下，谢谢！

@xiaoxian521

**Comment by xiaoxian521** [comment]
无法复现

**Comment by xiaoxian521** [comment]
具体自己看https://github.com/xiaoxian521/vue-pure-admin/commit/007bb0124fd8e9886f5c5bd3bf11efacea8d2c96
