### ISSUE TITLE
static clearAll(t, e) { Object.keys(e).forEach((s) => 报错

### ISSUE THREAD

**Issue by wanjingzhang** [xiaoxian521/responsive-storage#2]
当我启动项目的时候，clearAll方法报错，原因是e undefined。
![image](https://user-images.githubusercontent.com/26217235/182795593-292dd379-e737-4477-b5d9-41545d6066c7.png)

| 组件名称         | 版本号   | 用途               |
| ---------------- | ------- | ----------------- |
| node             | 14.17.5 | web 打包工具       |
| vite             | 2.9.14  | vue 脚手架打包工具 |
| vue              | 3.2.37  | 前端基于 MVVN 的   |
| typescript       | 4.6.4   | 编译开发语言       |
| less             | 4.1.3   | css 预编译语言     |
| pinia            | 2.0.16  | 消息状态管理       |
| vue-router       | 4.1.2   | 路由管理           |
| axios            | 0.27.2  | 接口请求组件       |

**Comment by xiaoxian521** [comment]
请提供复现仓库 memory为必传项

**Comment by WoJiaoFuXiaoYun** [comment]
> 请提供复现仓库 memory为必传项

我觉得memory即使为必填，也不应报错。当前错误在pure中会导致页面渲染失败

**Comment by xiaoxian521** [comment]
https://github.com/xiaoxian521/pure-admin-thin/commit/13427998f3cdb8fb109d4c1c6a8995103592a420#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L52
