### ISSUE TITLE
更新vue 3.2.47后无法使用

### ISSUE THREAD

**Issue by tongwenfei** [xiaoxian521/responsive-storage#5]
src/utils/responsive.ts:40:3 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(plugin: Plugin_2<[options: StorageOpts]>, options: StorageOpts): App<any>', gave the following error.
    Argument of type '{ nameSpace: string; memory: { locale: any; layout: any; configure: any; } & ({ tags: any; } | { tags?: undefined; }); }' is not assignable to parameter of type 'StorageOpts'.
      Property 'version' is missing in type '{ nameSpace: string; memory: { locale: any; layout: any; configure: any; } & ({ tags: any; } | { tags?: undefined; }); }' but required in type 'StorageOpts'.
  Overload 2 of 2, '(plugin: Plugin_2<[options: StorageOpts]>, options: [options: StorageOpts]): App<any>', gave the following error.
    Argument of type '{ nameSpace: string; memory: { locale: any; layout: any; configure: any; } & ({ tags: any; } | { tags?: undefined; }); }' is not assignable to parameter of type '[options: StorageOpts]'.
      Object literal may only specify known properties, and 'nameSpace' does not exist in type '[options: StorageOpts]'.

40   app.use(Storage, { nameSpace, memory: configObj });
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/.pnpm/responsive-storage@2.1.0/node_modules/responsive-storage/dist/index.d.ts:4:5
    4     version: Version;
          ~~~~~~~
    'version' is declared here.


Found 2 errors in 2 files.

**Comment by xiaoxian521** [comment]
暂时不要更新 对于刚发版的东西 尤其是改了很多东西的库 先等几天在更新 因为很可能存在隐藏 `bug`

**Comment by xiaoxian521** [comment]
Update the latest version has been fixed

**Comment by halcyonLife** [comment]
将@src/utils/responsive.ts文件中的app.use代码改为如下：

**Comment by xiaoxian521** [comment]
无需这么处理 升级最新版
